services:
  web:
    image: nhampp/leaguestats:ssl_staging
    build:
      context: ./LeagueStats
      dockerfile: Dockerfile.prod
    command: gunicorn LeagueStats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/LeagueStats/web/static
    expose:
      - 8000
    env_file:
      - .env.staging
    depends_on:
      - db
  db:
    image: c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.staging.db
  nginx-proxy-staging:
    image: nhampp/nginx-proxy:ssl_staging
    container_name: nginx-proxy-staging
    build: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/LeagueStats/web/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt-staging:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt-staging
    env_file:
      - .env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      -  nginx-proxy-staging

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
