services:
  web:
    image: leaguestats:latest
    build:
      context: ./LeagueStats
      dockerfile: Dockerfile.prod
    command: gunicorn LeagueStats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/LeagueStats/web/static
    #expose port to other docker containers
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/LeagueStats/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: