global:
  resolve_timeout: 5m

route:
  receiver: gmail-notifications

receivers:
- name: gmail-notifications
  email_configs:
  - to: noah.hampp@gmail.com
    from: leaguenetstats@gmail.com
    smarthost: 'smtp.gmail.com:587'
    auth_username: leaguenetstats@gmail.com
    auth_identity: leaguenetstats@gmail.com
    auth_password: cqfxzvmkassainuz
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - dev
      - instance
