# Generated by Django 3.1.5 on 2021-02-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210218_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_id',
            field=models.CharField(default='gaggiid', max_length=512),
            preserve_default=False,
        ),
    ]
