global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
          - league-netstats.ethz.ch:80

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093