global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
          - leaguestats-staging:8000

rule_files:
  - rules.yml