# Generated by Django 3.1.5 on 2021-02-23 17:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('time', models.IntegerField()),
                ('ping', models.IntegerField()),
                ('jitter', models.IntegerField()),
                ('in_bandwidth', models.FloatField()),
                ('out_bandwidth', models.FloatField()),
                ('loss', models.FloatField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('timestamp', models.PositiveIntegerField()),
                ('exp', models.PositiveIntegerField()),
                ('gold', models.IntegerField()),
                ('creep_score', models.IntegerField()),
                ('neutral_score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('active_participant', models.CharField(blank=True, max_length=2, null=True)),
                ('passive_participant', models.PositiveIntegerField(blank=True, null=True)),
                ('assisting_participants', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('type', models.CharField(max_length=32)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('queue_id', models.CharField(max_length=32)),
                ('game_type', models.CharField(max_length=64)),
                ('game_duration', models.BigIntegerField()),
                ('platform_id', models.CharField(max_length=8)),
                ('game_start', models.BigIntegerField()),
                ('season_id', models.CharField(max_length=32)),
                ('map_id', models.PositiveSmallIntegerField()),
                ('game_mode', models.CharField(max_length=64)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), max_length=10, size=None)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'match_id')},
            },
        ),
    ]
