# Generated by Django 3.1.5 on 2021-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0002_auto_20210224_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='participants',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
