# Generated by Django 3.1.5 on 2021-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0002_auto_20210505_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='frame',
            name='match_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='match_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
