# Generated by Django 3.1.5 on 2021-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0003_auto_20210304_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active_participant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='passive_participant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
