# Generated by Django 3.1.5 on 2021-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0003_auto_20210505_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='won',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
