# Generated by Django 3.1.5 on 2021-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='noah.hamp@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
